#!/usr/bin/env python3
# File: select_seeds.py
# Description: Selects new seeds for the next OFLOOD cycle by identifying outliers and validating their G-factors.

import argparse
import logging
import os
import random
import subprocess
import sys
import tempfile
import warnings
import shutil
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path


warnings.filterwarnings("ignore", category=UserWarning)
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    import MDAnalysis as mda
except ImportError:
    print("[ERROR] MDAnalysis is not installed.")
    sys.exit(1)

try:
    from dbscan import cluster_data
except ImportError:
    print("[ERROR] dbscan.py not found in the same directory.")
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] [%(asctime)s] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S%z",
)
logger = logging.getLogger(__name__)
logging.getLogger("MDAnalysis").setLevel(logging.WARNING)

RANDOM_SEED = 42


def evaluate_gfactor(
    cand, work_root_dir, topology_file_name, traj_file_name, procheck_dir, tmp_root_dir
):
    cycle_id = cand["cycle"]
    md_id = cand["md"]
    frame = cand["frame"]

    src_md_dir = work_root_dir / f"cycle_{cycle_id:03d}" / f"md_{md_id:03d}"
    traj_file = src_md_dir / traj_file_name

    if topology_file_name.is_absolute():
        topology_file = topology_file_name
    else:
        topology_file = src_md_dir / topology_file_name

    if not traj_file.exists() or not topology_file.exists():
        print(f"[ERROR] File not found: {traj_file} or {topology_file}")
        return None

    with tempfile.TemporaryDirectory(dir=tmp_root_dir) as tmp_dir_str:
        tmp_dir = Path(tmp_dir_str)
        pdb_file = tmp_dir / "seed.pdb"

        try:
            u = mda.Universe(str(topology_file), str(traj_file))
            protein = u.select_atoms("protein")
            _ = u.trajectory[frame]
            protein.write(str(pdb_file))
        except Exception as e:
            print(f"[ERROR] MDAnalysis error: {e}")
            return None

        procheck_scr_file = procheck_dir / "procheck.scr"
        if not procheck_scr_file.exists():
            return None

        try:
            env = os.environ.copy()
            env["prodir"] = str(procheck_dir)
            subprocess.run(
                [str(procheck_scr_file), "seed.pdb", "2.0"],
                cwd=str(tmp_dir),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=10,
                env=env,
            )
        except Exception as e:
            print(f"[ERROR] PROCHECK subprocess failed: {e}")
            return None

        sum_file = tmp_dir / "seed.sum"
        if not sum_file.exists():
            print(f"[ERROR] seed.sum not generated by PROCHECK in {tmp_dir}")
            return None

        try:
            with open(sum_file, "r") as f:
                for line in f:
                    if "G-factor" in line:
                        parts = line.split("Overall:")
                        if len(parts) > 1:
                            val_str = parts[1].split()[0]
                            cand["g_factor"] = float(val_str)
                            print(
                                f"[INFO] Cycle {cycle_id} MD {md_id} Frame {frame}: G-factor = {cand['g_factor']}"
                            )
                            return cand
        except Exception as e:
            print(f"[ERROR] Parsing sum_file error: {e}")
            return None

    print(
        f"[ERROR] G-factor not found in seed.sum for Cycle {cycle_id} MD {md_id} Frame {frame}"
    )
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-file", type=Path, required=True)
    parser.add_argument("--output-file", type=Path, required=True)
    parser.add_argument("--work-root-dir", type=Path, required=True)
    parser.add_argument("--topology-file-name", type=Path, required=True)
    parser.add_argument("--traj-file-name", type=str, required=True)
    parser.add_argument("--procheck-dir", type=Path, required=True)
    parser.add_argument("--eps", type=float, required=True)
    parser.add_argument("--min-samples", type=int, required=True)
    parser.add_argument("--n-seeds", type=int, required=True)
    parser.add_argument("--g-factor-threshold", type=float, required=True)
    parser.add_argument("--max-workers", type=int, required=True)
    parser.add_argument("--n-cv", type=int, default=2)
    args = parser.parse_args()

    random.seed(RANDOM_SEED)

    procheck_scr_file = args.procheck_dir / "procheck.scr"
    if not procheck_scr_file.exists():
        logger.error(f"PROCHECK executable not found at {procheck_scr_file}")
        sys.exit(1)

    with tempfile.TemporaryDirectory() as base_tmp_dir_str:
        base_tmp_dir = Path(base_tmp_dir_str)

        try:
            cluster_data(args.input_file, base_tmp_dir, args.eps, args.min_samples, args.n_cv)
        except SystemExit:
            logger.error("Clustering step failed.")
            sys.exit(1)

        outliers_file = base_tmp_dir / "outliers.txt"
        if not outliers_file.exists():
            logger.error("Clustering failed to produce outliers.txt.")
            sys.exit(1)

        n_cv = args.n_cv
        candidates = []
        with open(outliers_file, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) >= n_cv + 3:
                    candidates.append(
                        {
                            "cvs": [float(parts[i]) for i in range(n_cv)],
                            "cycle": int(float(parts[n_cv])),
                            "md": int(float(parts[n_cv + 1])),
                            "frame": int(float(parts[n_cv + 2])),
                        }
                    )

        print(f"[INFO] Found {len(candidates)} candidates from outliers.txt")

        random.shuffle(candidates)
        valid_seeds = []

        with ProcessPoolExecutor(max_workers=args.max_workers) as executor:
            batch_size = args.max_workers
            for i in range(0, len(candidates), batch_size):
                batch = candidates[i : i + batch_size]
                futures = {
                    executor.submit(
                        evaluate_gfactor,
                        cand,
                        args.work_root_dir,
                        args.topology_file_name,
                        args.traj_file_name,
                        args.procheck_dir,
                        base_tmp_dir,
                    ): cand
                    for cand in batch
                }

                for future in as_completed(futures):
                    try:
                        result = future.result()
                    except Exception as e:
                        logger.warning(f"Worker failed: {e}")
                        continue

                    if (
                        result is not None
                        and result["g_factor"] >= args.g_factor_threshold
                    ):
                        valid_seeds.append(result)

                if len(valid_seeds) >= args.n_seeds:
                    break

        if len(valid_seeds) == 0:
            logger.warning("No valid seeds found satisfying the G-factor threshold.")
        elif len(valid_seeds) < args.n_seeds:
            logger.warning(
                f"Only {len(valid_seeds)} valid seeds found (requested {args.n_seeds})."
            )

        selected_seeds = valid_seeds[: args.n_seeds]

        try:
            with open(args.output_file, "w") as f:
                for seed in selected_seeds:
                    cv_str = " ".join(f"{v:.5f}" for v in seed["cvs"])
                    f.write(
                        f"{cv_str} {seed['cycle']} {seed['md']} {seed['frame']}\n"
                    )

            analysis_dir = args.output_file.parent
            if outliers_file.exists():
                shutil.copy(outliers_file, analysis_dir / "outliers.txt")

            cluser_file = base_tmp_dir / "clustered_points.txt"
            if cluser_file.exists():
                shutil.copy(cluser_file, analysis_dir / "clustered_points.txt")

        except IOError as e:
            logger.error(f"Failed to write to {args.output_file}: {e}")
            sys.exit(1)


if __name__ == "__main__":
    main()
