#!/usr/bin/env bash
# File: compute_cv.sh
# Description: calculate collective variables using cpptraj
set -euo pipefail

_traj_file="${1}"
_top_file="${2}"
_structure_file="${3}"
_out_file="${4}"
_cycle_id="${5}"
_temp_dir=$(mktemp -d)

_md_dir=$(dirname "${_traj_file}")
_md_dirname=$(basename "${_md_dir}")
_md_id=$(echo "${_md_dirname}" | sed 's/md_0*//')
if [[ -z "${_md_id}" ]]; then
  _md_id=1
fi

_cpptraj_in_file="${_temp_dir}/cv.in"
cat <<EOF >"${_cpptraj_in_file}"
parm ${_top_file}
trajin ${_traj_file}
unwrap :1-271
center :1-271@CA mass origin
autoimage
angle hinge :1-100,236-259 :101-107,232-235,260-268 :108-231,269-271 mass
dihedral twist :1-100,236-259 :99-100,236-237,258-259 :108-109,230-231,269-270 :108-231,269-271 mass
run
writedata cv.dat hinge twist
quit
EOF

(
  cd "${_temp_dir}" || exit 1
  cpptraj -i cv.in >cpptraj.log 2>&1
)

if [[ -f "${_temp_dir}/cv.dat" ]]; then
  awk -v m="${_cycle_id}" -v i="${_md_id}" 'NR>1 {printf "%5f  %5f  %d  %d  %d\n", $2, $3, m, i, ($1 - 1)}' "${_temp_dir}/cv.dat" >"${_out_file}"
else
  echo "[ERROR] cv.dat was not generated by cpptraj." >&2
  cat "${_temp_dir}/cpptraj.log" >&2
  rm -rf "${_temp_dir}"
  exit 1
fi

rm -rf "${_temp_dir}"
